---
- hosts: root
  roles:
    - securisation

- hosts: user
  roles:
    - basic-services
    # - newrelic
    - docker-install
    - reverse-proxy
    - seedbox
    - files
    - cadvisor
    - owncloud

# Run the following command to launch the playbook and roles.
# ansible-playbook -b --ask-sudo-pass main.yml -i hosts
